SET NAMES 'utf8';
SET CHARACTER SET utf8;

INSERT IGNORE INTO `users`
(`id`, `username`, `name`, `email`, `password`, `state`, `created_on`) VALUES
(1, 'admin', null, null, null, 1, null);

INSERT IGNORE INTO `users`
(`id`, `username`, `name`, `email`, `password`, `state`, `created_on`) VALUES
(2, 'maghsoud', 'mohamad maghsoud', 'msmaghsoud@ut.ac.ir', null, 1, null);



INSERT IGNORE INTO `machines`
(`id`, `name`, `title`, `note`, `state`, `created_on`) VALUES
(1, 't-130mm', 'توپ ۱۳۰ م.م', null, null, null);

INSERT IGNORE INTO `machine_types`
(`id`, `machine_id`, `name`, `state`, `created_on`) VALUES
(1, 1, 'خرج کامل', null, null);


INSERT IGNORE INTO `machine_details`
(`id`, `machine_types_id`, `distance`, `deg_mil`    , `deg_bar`, `deg_bar_b`, `top`,    `cor_dir`,      `cor_dir_w`, `cor_dis_w`, `cor_dis_p`, `cor_dis_air_tem`, `cor_dis_s`, `cor_dis_tem`, `cor_dis_wg`, `cor_dis_mil`,              `dis_deg`, `b`, `deg`, `land_deg`, `speed`, `flight_time`, `err_dis`, `err_h`, `err_dir`, `state`, `created_on`) VALUES
(null, 1 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 ,0 , null, 0, null, null, null, null, null),
(null, 1 ,200 ,1 ,null ,null ,null ,0,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, 0.2, null, null, null, null, null),
(null, 1 ,400 ,2 ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,600 ,3 ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,800 ,4 ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,1000 ,6 ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,1200 ,7 ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,1400 ,8 ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,1600 ,9 ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,1800 ,11 ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,2000 ,12 ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,2200 ,13 ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,2400 ,14 ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,2600 ,16 ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,2800 ,17 ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,3000 ,18 ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,3200 ,20 ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,3400 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,3600 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,3800 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,4000 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,4200 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,4400 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,4600 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,4800 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,5000 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,5200 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,5400 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,5600 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,5800 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,6000 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,6200 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,6400 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,6800 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,7000 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,7200 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,7400 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,7600 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,7800 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,8000 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,8200 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,8400 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,8600 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,8800 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,9000 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,9200 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,9400 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,9600 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,9800 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,10000 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,10200 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,10400 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,10600 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,10800 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,10800 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,11000 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,11200 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,11400 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,11600 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,11800 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,12000 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,12200 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,12400 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,12600 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,12800 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,13000 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,13200 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,13400 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,13600 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,13800 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,14000 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,14200 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,14400 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,14600 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,14800 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,15000 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,15200 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,15400 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,15600 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,15800 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,16000 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,16200 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,16400 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,16600 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,16800 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,17000 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,17200 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,17400 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,17600 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,17800 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,18000 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,18200 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,18400 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,18600 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,18800 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,19000 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,19200 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,19400 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,19600 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,19800 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,20000 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,20200 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,20400 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,20600 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,20800 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,21000 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,21200 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,21400 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,21600 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,21800 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,22000 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,22200 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,22400 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,22600 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,22800 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,23000 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,23200 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,23400 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,23600 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,23800 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,24000 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,24200 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,24400 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,24600 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,24800 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,25000 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,25200 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,25400 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,25600 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,25800 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,26000 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,26200 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,26400 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,26600 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,26800 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,27000 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,27200 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,27400 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,27490 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,27600 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null),
(null, 1 ,30000 ,null ,null ,null ,null ,null,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null ,null , null, null, null, null, null, null, null);